name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install LLVM
        run: choco install llvm -y

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Build
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: cargo build --release

      - name: sccache stats
        run: sccache --show-stats

      - name: Prepare Artifact
        run: |
          mkdir dist
          Get-ChildItem -Path target/release -Filter tree-pdf-viewer.exe -Recurse | Copy-Item -Destination dist/
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree-pdf-viewer
          path: dist/
